### ISSUE TITLE
Remove stray TODO and empty else condition

### ISSUE THREAD

**Issue by skliper** [nasa/CS#40]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/CS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [README file](https://github.com/nasa/CS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
https://github.com/nasa/CS/blob/4280e14e841a2559400dfc0372de25d1506a56ff/fsw/src/cs_eeprom_cmds.c#L318-L321

**Describe the solution you'd like**
There's no action for the else case, remove (along with the TODO note).

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC
